# Site settings
author: Isiah Cruz
title: Apollo 2020
header-img: img/home-bg.png
email: cruzisiah@gmail.com
copyright_name: Isiah Cruz
description: > # this means to ignore newlines until "baseurl:"
  My journey from Ops Specialist to Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cruzisiah

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
